import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/resources/1.css/global.css";
import { gt_america_mono } from "./(libs)/fonts";
import clsx from "clsx";
import { DarkModeProvider } from "@/wrappers/darkMode";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={clsx(gt_america_mono.className)}>

      <body className="">
        <DarkModeProvider>
          <Main>
            {children}
          </Main>
        </DarkModeProvider>
      </body>

    </html>
  );
}

const Main = ({ children }: { children: React.ReactNode }) => {

  return (
    <div className="flex flex-col justify-between bg-light dark:bg-dark justify-between overflow-hidden" style={{ height: "100vh", width: "100vw" }}>
      <div className='grow flex flex-1 justify-center overflow-hidden relative z-0'>
        {children}
      </div>
    </div>
  )
}